### ISSUE TITLE
fuzzyfiles preview panel alway show not found file 

### ISSUE THREAD

**Issue by guxingke** [Donaldttt/fuzzyy#1]
<img width="1728" alt="image" src="https://github.com/Donaldttt/fuzzyy/assets/7038315/9d78a736-3e12-4dda-ad76-56bab97c283b">

----
it looks like has space char at line head. 

and  it works well in terminal , buf failed in MacVim

**Comment by Donaldttt** [comment]
Yeah you are right, the space was causing the issue. For some reason the width of devicon in macvim is 2 but its width is 1 in terminal. It should be fixed by the latest commit since it will check the width of devicon now.
