### ISSUE TITLE
How to i open them in split and tab?

### ISSUE THREAD

**Issue by justrajdeep** [Donaldttt/fuzzyy#11]
Hi 

I am currently using `FuzzyBuffers`. How do i open the files in `:vs`/`:sp` or `:tab`?

Thanks

**Comment by Donaldttt** [comment]
In the lastest version you can split buffer vertically/horizontally in FuzzyBuffers by pressing `ctrl + v` or `ctrl + s`. Later I will add support for \:tab after I am more familiar with that feature.

**Comment by Donaldttt** [comment]
`ctrl + t` opens selected file in a new tab page in the latest version.

**Comment by justrajdeep** [comment]
Thank you so much for the super prompt fix
