### ISSUE TITLE
Disable preview window

### ISSUE THREAD

**Issue by ilango100** [Donaldttt/fuzzyy#12]
Is there a way to disable the preview window?
I haven't found anything in the documentation or the options.

I used to disable preview window in FZF using:
```vim9script
g:fzf_preview_window = []
```

Usually preview window is a useful feature, but sometimes there are some ftplugins that cause issues like chrisbra/csv.vim.
My preference is to disable it too, as I don't like unnecessary IO of reading a file when I've not decided to open it.

Thanks a lot for the plugin!

**Comment by Donaldttt** [comment]
Hi, I just add support for windows layout configuration. You can disable preview windows for commands by adding something like this `let g:fuzzyy_window_layout = { 'FuzzyFiles': { 'preview': 0 } }` in your vimrc (which will only disable the preview windows for FuzzyFiles command). More information is in the Readme. Let me know if you run into any bugs.
