### ISSUE TITLE
Splitting terminal buffer using :FuzzyBuffers opens incorrect buffer

### ISSUE THREAD

**Issue by ilango100** [Donaldttt/fuzzyy#13]
When using :FuzzyBuffers to select a terminal buffer opened by `:term` works fine, but it fails to open the proper buffer when using split or tab keymaps `<C-s>`, `<C-v>` or `<C-t>`.

To reproduce:
```
# Open vim
:terminal
<C-w>c  # closes terminal window
:FuzzyBuffers
# Select terminal buffer
<C-s>
```

It works fine if I use `<CR>` instead of `<C-s>` or `<C-v>`

Once again, thanks for the plugin and quick response to issues!

**Comment by Donaldttt** [comment]
Thank you for the bug report. This issue should be fixed in the latest commit.
