### ISSUE TITLE
`:FuzzyBuffers` - Can it work like `:ls` ?

### ISSUE THREAD

**Issue by shuckster** [Donaldttt/fuzzyy#15]
Thank you for creating this plugin.

Is it possible for `:FuzzyBuffers` to offer the same listing as `:ls` please?

**Comment by shuckster** [comment]
I found [the line](https://github.com/Donaldttt/fuzzyy/blob/vim9/autoload/fuzzy/buffers.vim#L62) in question:

```vim
    var buf_data = getbufinfo({'buflisted': 1, 'bufloaded': 1})
```

Changing 'bufloaded' from 1 to 0 got me what I wanted.

**Comment by Donaldttt** [comment]
Thank you for the help. Could you give me an example when buffers filtered by "{'buflisted': 1, 'bufloaded': 1}" will get different result than :ls command?

**Comment by shuckster** [comment]
Thanks for the reply.

Yes, my `:ls` command seems to include buffers from the MRU list, as well as those that are currently open. `:FuzzyBuffers` includes only buffers that are opened in splits or tabs.

Perhaps that's correct behaviour though? I wonder if I was just mistaken in my understanding of what `:FuzzyBuffers` should do?

I may undo my change to bufloaded and assign `<leader>ft` to `:FuzzyMRU`.

**Comment by Donaldttt** [comment]
Yes, in my design, FuzzyBuffers is supposed to search the buffers that you have opened in one edit. I will update the readme to make it more clear.
