### ISSUE TITLE
[Feature Request] Readline bindings for the finder prompt

### ISSUE THREAD

**Issue by Andilutten** [Donaldttt/fuzzyy#17]
I'm not sure if its just me, but I am very dug in on using the readline keybindings when navigating a line editor.
Ctrp-{p,n} is implemented and works great, but i would like to be able to use Ctrl-{a,k,e} do navigate to the beginning and end of the line aswell as kill the line completly.

Is there anyway for me to create these mappings using the current state of the plugin ? 

Killer plugin tho! Love it
Best regards

**Comment by Donaldttt** [comment]
Hi, in the lastest version ctrl-{a, e, k} will do what you want. You can also override them by changing keymaps.
