### ISSUE TITLE
no color with fb but ff and ft have color

### ISSUE THREAD

**Issue by hydrasho** [Donaldttt/fuzzyy#18]
no color file with \fb

![image](https://github.com/Donaldttt/fuzzyy/assets/40312793/d9f39e6d-3725-473e-bb7a-5f8a5704bb6a)

but color work with \ff and \ft

![image](https://github.com/Donaldttt/fuzzyy/assets/40312793/f9d90890-c44f-410e-9632-9ffe05dd46fa)

can you add color file in \fb please thank !

**Comment by Donaldttt** [comment]
We can easily add color to 'fb'. It's just the color will be meaningless and the look is not very good. Vim add color to code according to the syntax. However, if you try to search something in a buffer, the lines will be rearrange randomly or even filered out. Therefore there will be no syntax after searching.

**Comment by hydrasho** [comment]
this plugin https://github.com/hahdookin/minifuzzy.vim
does it, and that's why I thought it was easy to do, it even keeps the colour during the search

**Comment by Donaldttt** [comment]
I just checked out this plugin, and it actually has the problem I was talking about. As you can see, It's highlight is complelety messed up when I tried to search something. 
![屏幕截图 2023-12-24 000943](https://github.com/Donaldttt/fuzzyy/assets/38392952/88e6eec4-16e0-4b1f-890c-e3eca93705d1)
