### ISSUE TITLE
E121: Undefined variable: files

### ISSUE THREAD

**Issue by craigmac** [Donaldttt/fuzzyy#2]
I get this error for all of the defined commands (replace 'files' with 'colors', 'ag', etc.), updated to latest commit just now and I'm on macvim 9.0.1403.

**Comment by Donaldttt** [comment]
Hi, 

I am not able to reproduce this error using macvim 9.0.1403 with the following minimal configuration .vimrc. 

```vim
set rtp+=~/.vim/plugged/fuzzyy
let mapleader=","
```
Are you using any plugin manager and if you have time could you try if you can reproduce this error with minimal configuration?

**Comment by Donaldttt** [comment]
I think I found the problem it seems when a vim9script reloads its script-local functions and variables will all be deleted. It should be fixed by the latest commit.
