### ISSUE TITLE
Layout for FuzzyGrep is ignored 

### ISSUE THREAD

**Issue by iddoeldor** [Donaldttt/fuzzyy#23]
First of all, thank you, this tool is truly commendable.

For FuzzyFiles it works but for FuzzyGrep is ignored

```
g:fuzzyy_window_layout = {
    'FuzzyGrep': { 'preview': 1, 'preview_ratio': 0.5, 'width': 0.98, },
```

https://github.com/Donaldttt/fuzzyy/blob/b79d4c6f55744c4b9ece16b6fd57b26aa367b6cf/autoload/fuzzy/ag.vim#L299

**Comment by Donaldttt** [comment]
> also, if requested i'll open new issue in a large file, 27K LOC, using FuzzyBuffer takes 15seconds for 5 letter word because it executes the grep for each letter i suggest, if easily possible, to listen execute when user finish typing

Yes, A new issue would be great. Could you provide a example file if it is convenient for you? And what os are you using and what's the spec of your machine?

**Comment by Donaldttt** [comment]
> First of all, thank you, this tool is truly commendable.
> 
> For FuzzyFiles it works but for FuzzyGrep is ignored
> 
> ```
> g:fuzzyy_window_layout = {
>     'FuzzyGrep': { 'preview': 1, 'preview_ratio': 0.5, 'width': 0.98, },
> ```
> 
> https://github.com/Donaldttt/fuzzyy/blob/b79d4c6f55744c4b9ece16b6fd57b26aa367b6cf/autoload/fuzzy/ag.vim#L299

This bug should be fix in the latest commit.
