### ISSUE TITLE
General use of fuzzy finder

### ISSUE THREAD

**Issue by jeslinmx** [Donaldttt/fuzzyy#24]
Is there any way to use the fuzzy finder to filter arbitrary data? (e.g. by piping in commit history from Git)

Got the idea from fzf.vim, which uses `fzf` to filter through commit history, in addition to jumps, marks, :- and /-history, and others.

**Comment by Donaldttt** [comment]
Are you suggesting a command, for example, called FuzzyFilter that accepts a list as its parameter and then opens a search window for that list?

**Comment by jeslinmx** [comment]
Yup! Although after reading your reply, I do realize the same thing can be achieved a similar result, using a temporary buffer and FuzzyInBuffer.
