### ISSUE TITLE
Feature request: Sort FuzzyBuffers by last access

### ISSUE THREAD

**Issue by sindrom91** [Donaldttt/fuzzyy#26]
It would be nice if there was an option to list buffers by most recent access instead of name.

**Comment by Donaldttt** [comment]
This feature is added in the latest commit.

**Comment by sindrom91** [comment]
This doesn't seem to work for me. Order always seems to be the same.

**Comment by sindrom91** [comment]
It works fine for me what I change the sorting function in the following way:
```vim
        return buf_dict[a][3] == buf_dict[b][3] ? 0 :
               buf_dict[a][3] <  buf_dict[b][3] ? 1 : -1
```
