### ISSUE TITLE
E1048: Item not found in script

### ISSUE THREAD

**Issue by Gismu** [Donaldttt/fuzzyy#27]
Functions don't work.
When the command is executed, showing the following message.

```
Error detected while compiling function fuzzy#ag#Start:
line   34:
E1048: Item not found in script: SetPrompt
```
or
```
Error detected while compiling function fuzzy#files#Start:
line   18:
E1048: Item not found in script: split_edit_callbacks
Press ENTER or type command to continue
```

![Screenshot_20240614_171914](https://github.com/Donaldttt/fuzzyy/assets/21137457/a322bc5b-c8dc-4828-b5f0-2c91f0aa913a)

**Comment by Donaldttt** [comment]
Hi. I saw you pull request. However, isn't the changed path same as the original one(eg. 'utils/selector.vim' and '../utils/selector.vim')? Could you explain to me what is the differences or why the latter fix the problem?

**Comment by Donaldttt** [comment]
> #28

Also I could not reproduce this bug in my machine. Could you tell me what OS you ran into this bug?

**Comment by Gismu** [comment]
I just upgraded my vim into version 9.1.496.
It fixed the bug.
I thought it was bug from vim, not this plugin.

Thank you for your attention.
