### ISSUE TITLE
unlisted scratch buffers leakage.

### ISSUE THREAD

**Issue by ubaldot** [Donaldttt/fuzzyy#34]
After having made few searches, I notice a long list of unlisted scratch buffers (check with `:ls u`). It looks like a buffer leakage.
Possible solution: close them in the callback functions. 

![image](https://github.com/user-attachments/assets/69f1ff31-d355-4607-8966-b0c8d1b270da)

**Comment by Donaldttt** [comment]
It should be fixed in the latest commit.
