### ISSUE TITLE
[Feature Request] Support for MRU (most recently used) with file preview.

### ISSUE THREAD

**Issue by debajyoti1990** [Donaldttt/fuzzyy#4]

**Comment by Donaldttt** [comment]
Check out the latest version. You can set `g:enable_fuzzyy_MRU_files = 1` to enable FuzzyMRUFiles command. More information is in the Readme.

**Comment by debajyoti1990** [comment]
Thanks @Donaldttt , you are awesome man ! I wonder why this repo is not getting stars yet !!

**Comment by Donaldttt** [comment]
No problem man! This is also a fun experience for me.
