### ISSUE TITLE
[FEAT REQUEST]: use findstr for :FuzzyGrep in Windows.

### ISSUE THREAD

**Issue by ubaldot** [Donaldttt/fuzzyy#40]
At the moment, `:FuzzyGrep` in Windows returns error complaining that `ag, rg or grep` should be installed. However, windows has `findstr` instead.

Could that be used for `:FuzzyGrep` in Windows?  For example running `powershell -command "findstr /s /i /n <string> <pwd>"` or similar?

See [here](https://stackoverflow.com/questions/87350/what-are-good-grep-tools-for-windows).

**Comment by ubaldot** [comment]
Thank you! I gave it a shot tonight, it works fine, with the exception that `g:fuzzyy_files_ignore_dir` does not seem to have any influence (not sure about `g:fuzzyy_files_ignore_files`). I added `.git` folder but it appears in the results. On Linux it seems to work well. 

Also, in the README.md there is a `var` that should be a `let`.

**Comment by Donaldttt** [comment]
> Thank you! I gave it a shot tonight, it works fine, with the exception that `g:fuzzyy_files_ignore_dir` does not seem to have any influence (not sure about `g:fuzzyy_files_ignore_files`). I added `.git` folder but it appears in the results. On Linux it seems to work well. 
> 
> Also, in the README.md there is a `var` that should be a `let`. 

It's expected. However I will keep this in mind to see if there are way to make fuzzygrep respect these two options.
