### ISSUE TITLE
[FEATURES REQUEST]: hotkey for deleting selected buffer in FuzzyBuffers

### ISSUE THREAD

**Issue by nooncat** [Donaldttt/fuzzyy#46]
Is it possible to add hotkey(Ctrl + k for example) for deleting selected buffer from FuzzyBuffers list?

**Comment by Donaldttt** [comment]
This feature is added in the latest commit. You can set the keymap to enable this feature: 

" FuzzyBuffer keymap for commands speicific to FuzzyBuffers
" default to is the following
let g:fuzzyy_buffers_keymap = {
\    'delete_buffer': "",
\    'close_buffer': "\<c-l>",
\ }

**Comment by nooncat** [comment]
@Donaldttt, thank you!
