### ISSUE TITLE
[Feature Request] Can we enable grepping word under cursor

### ISSUE THREAD

**Issue by blayz3r** [Donaldttt/fuzzyy#5]
Something like this:

`FuzzyGrep <C-R><C-W><CR>`

Great Plugin btw!

**Comment by Donaldttt** [comment]
Thank you! In the latest version, you can define keymaps like `nnoremap <Space>f :FuzzyGrep <C-R><C-W><CR>` in your config to grep search word under cursor. More detail is in the README.

**Comment by blayz3r** [comment]
Amazing!!
