### ISSUE TITLE
FuzzyCommands causes cursor to disappears

### ISSUE THREAD

**Issue by toooonyy** [Donaldttt/fuzzyy#50]
```
OS: macOS 15.1.1 arm64
vim: 9.1.0850
Plug: all update to date
shell: fish/zsh
Terminal: wezterm/apple terminal
```

Plug list and maybe relate setting?
```
Plug '00dani/SchemaStore.vim', {'for': ['json', 'jsonc']}
Plug 'sheerun/vim-polyglot'
Plug 'yegappan/lsp'
Plug 'saccarosium/yegappan-lsp-settings'
Plug 'girishji/vimsuggest'
Plug 'girishji/vimcomplete'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'rafamadriz/friendly-snippets'
Plug 'lervag/vimtex', {'for': 'tex' }
Plug 'chrisbra/Colorizer'

Plug 'machakann/vim-sandwich'
Plug 'TaDaa/vimade'
# Plug 'pbrisbin/vim-mkdir'
Plug 'matze/vim-move'
Plug 'andymass/vim-matchup'
Plug 'LunarWatcher/auto-pairs'
Plug 'luochen1990/rainbow'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'dstein64/vim-startuptime', {'on': 'StartupTime'}
Plug 'girishji/vimbits'
Plug 'Donaldttt/fuzzyy'
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'tpope/vim-sleuth'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/seoul256.vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'ryanoasis/vim-devicons'
.......
.......
&t_SI = "\e[6 q" #SI = INSERT mode
&t_SR = "\e[4 q" #SR = REPLACE mode
&t_EI = "\e[2 q" #EI = NORMAL mode (ALL ELSE)

set cursorline


```

When I use vim build-in cmd to execute a command which leads to an error (in this case I just called lspdiag) and then vim complains this is all good. But if I do it through FuzzyCommands then it additionally says `Error detected while processing function <SNR>209_MenuFilter[28]..<SNR>209_GeneralPopupCallback[17]..<SNR>111_Select:` and now my cursor disappears and even if I quit vim it's still gone.

I tested with both zsh and fish and change my term emulator and still get the same result. 

Screenshots:

Normal error
![normal error](https://github.com/user-attachments/assets/cdff5db9-2c42-49df-bf88-2b65e578eac6)
FuzzyCommands error
![fuzzy error](https://github.com/user-attachments/assets/bb75b1c7-620e-4fa3-ab65-d3e477ca66dc)

------------------------------
Cursor disappears
![cursor gone](https://github.com/user-attachments/assets/8d6b1b54-a9d5-4cbc-826f-30f89ff538f2)
![cursor gone2](https://github.com/user-attachments/assets/0932cf85-a59b-4e64-8a00-63df38c73d52)

I'm not an expert in vim but search the keyword cursor in the file [autoload/utils/popup.vim](https://github.com/Donaldttt/fuzzyy/blob/75e1d1ad4d6914283bae5e611789a81630967d9c/autoload/utils/popup.vim) and I guess it tries to modifies cursor and due to the error stucks and didn't change it back? Explicitly setting &t_ve = "\e[?25h" doesn't help.

**Comment by Donaldttt** [comment]
This problem should be fixed in the latest commit. Please let me know if it works for you.

**Comment by toooonyy** [comment]
thx!
