### ISSUE TITLE
Feature request: fuzzy search only git files

### ISSUE THREAD

**Issue by xmready** [Donaldttt/fuzzyy#6]
Would love to see an option to only search files that are included in the current git repo. Fzf does this using fugitive.

**Comment by Donaldttt** [comment]
Check out the option
```vim
" only list git files for FuzzyFiles. like 'git ls-files'
" default to 0
let g:files_only_git_files = 1
```
in the latest version.

**Comment by xmready** [comment]
> Check out the option
> 
> ```viml
> " only list git files for FuzzyFiles. like 'git ls-files'
> " default to 0
> let g:files_only_git_files = 1
> ```
> 
> in the latest version.

This doesn't allow me the option to switch back and forth between searching all files and git files. I'm looking for separate functions

**Comment by Donaldttt** [comment]
Got it. I will add something similar to GFiles in fzf.

**Comment by Donaldttt** [comment]
Please cheak out the new FuzzyGitFiles command in the latest version.
